trigger:
- main

pool:
  name: Default  # Use the name of your self-hosted agent pool

variables:
  storageAccountName: 'mystorageaccount$(Build.BuildId)'
  fileShareName: 'myfileshare'
  containerAppName: 'mycontainerapp'
  location: 'northeurope'
  existingContainerAppEnvironmentName: 'managedEnvironment-RGmavishnoi-91ac-21march'
  dockerImage: 'manishvishnoi/gw22march:latest'
  localFilePath: 'C:\Users\mavishnoi\Downloads\license.lic'

stages:
- stage: Deploy
  displayName: Deploy Resources
  jobs:
  - job: DeployBicep
    displayName: Deploy Azure Resources
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Bicep'
      inputs:
        azureSubscription: 'axwaymanishdepops1'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group RG-mavishnoi `
          --template-file ./apigw.bicep `
          --parameters storageAccountName=$(storageAccountName) `
                       fileShareName=$(fileShareName) `
                       containerAppName=$(containerAppName) `
                       location=$(location) `
                       existingContainerAppEnvironmentName=$(existingContainerAppEnvironmentName) `
                       dockerImage=$(dockerImage)

  - job: UploadFile
    displayName: Upload File to File Share
    dependsOn: DeployBicep
    steps:
    - task: AzureCLI@2
      displayName: 'Upload File to Azure File Share'
      inputs:
        azureSubscription: 'axwaymanishdepops1'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $storageKey = (az storage account keys list --resource-group RG-mavishnoi --account-name $(storageAccountName) --query "[0].value" --output tsv)
          az storage file upload --account-name $(storageAccountName) --account-key $storageKey --share-name $(fileShareName) --source "$(localFilePath)"
