trigger:
  - main

pool:
  name: Default  # Ensure this matches your self-hosted agent pool

variables:
  storageAccountName: 'mystorageaccount$(Build.BuildId)'
  fileShareName: 'myfileshare'
  containerAppName: 'mycontainerapp'
  existingContainerAppEnvironmentName: 'managedEnvironment-RGmavishnoi-91ac-21march'
  dockerImage: 'manishvishnoi/gw22march:latest'
  localFilePath: 'C:\Users\mavishnoi\Downloads\license.lic'
  azureSubscription: 'axwaymanishdepops1'
  resourceGroup: 'RG-mavishnoi'
  location: 'northeurope'  # Set your Azure region

stages:
  - stage: Deploy
    displayName: Deploy Azure Resources
    jobs:
      - job: DeployResources
        displayName: Deploy Bicep Template
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy Bicep Template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create --resource-group $(resourceGroup) --template-file apigw.bicep \
                  --parameters storageAccountName=$(storageAccountName) fileShareName=$(fileShareName) \
                  containerAppName=$(containerAppName) dockerImage=$(dockerImage) \
                  location=$(location) existingContainerAppEnvironmentName=$(existingContainerAppEnvironmentName)

  - stage: UploadFile
    displayName: Upload File to Azure File Share
    jobs:
      - job: UploadFile
        displayName: Upload Local File
        steps:
          - task: AzureCLI@2
            displayName: 'Get Storage Account Key'
            name: GetStorageKey  # 👈 Required to reference output later
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                $storageKey = az storage account keys list --resource-group $(resourceGroup) --account-name $(storageAccountName) --query '[0].value' -o tsv
                echo "##vso[task.setvariable variable=STORAGE_KEY;isOutput=true]$storageKey"

          - task: AzureCLI@2
            displayName: 'Upload File to Azure File Share'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az storage file upload --account-name $(storageAccountName) --account-key $(GetStorageKey.STORAGE_KEY) --share-name $(fileShareName) --source "$(localFilePath)"
