trigger:
  - main

pool:
  name: Default  # Ensure this is the correct self-hosted agent pool

variables:
  storageAccountName: 'mystorageaccount$(Build.BuildId)'
  containerAppName: 'mycontainerapp'
  existingContainerAppEnvironmentName: 'managedEnvironment-RGmavishnoi-91ac-21march'
  dockerImage: 'manishvishnoi/gw22march:latest'
  azureSubscription: 'axwaymanishdepops1'
  resourceGroup: 'RG-mavishnoi'
  location: 'northeurope'  # Specify your Azure region here

stages:
  - stage: Deploy
    displayName: Deploy Azure Resources
    jobs:
      - job: DeployResources
        displayName: Deploy Bicep Template
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy Bicep Template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create --resource-group $(resourceGroup) --template-file apigw.bicep --parameters storageAccountName=$(storageAccountName) containerAppName=$(containerAppName) dockerImage=$(dockerImage) existingContainerAppEnvironmentName=$(existingContainerAppEnvironmentName) location=$(location)

  - stage: UploadFile
    displayName: Upload File to Azure File Share
    jobs:
      - job: UploadFile
        displayName: Upload Local File
        steps:
          - task: AzureCLI@2
            displayName: 'Get Storage Account Key'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                $storageKey = az storage account keys list --resource-group $(resourceGroup) --account-name $(storageAccountName) --query '[0].value' -o tsv
                Write-Host "##vso[task.setvariable variable=STORAGE_KEY;isOutput=true]$storageKey"

          - task: AzureCLI@2
            displayName: 'Upload File to Azure File Share'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az storage file upload --account-name $(storageAccountName) --account-key $(STORAGE_KEY) --share-name $(fileShareName) --source "$(localFilePath)"
